# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListConfigs(object):
    def setupUi(self, ListConfigs):
        ListConfigs.setObjectName("ListConfigs")
        ListConfigs.resize(362, 482)
        self.verticalLayoutWidget = QtWidgets.QWidget(ListConfigs)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 341, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.treeView = QtWidgets.QTreeView(self.verticalLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.pushButton_open = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)
        self.label_2 = QtWidgets.QLabel(ListConfigs)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 341, 31))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ListConfigs)
        QtCore.QMetaObject.connectSlotsByName(ListConfigs)

    def retranslateUi(self, ListConfigs):
        _translate = QtCore.QCoreApplication.translate
        ListConfigs.setWindowTitle(_translate("ListConfigs", "ListConfigs"))
        self.label.setText(_translate("ListConfigs", "Choose file:"))
        self.pushButton_open.setText(_translate("ListConfigs", "Open"))
        self.label_2.setText(_translate("ListConfigs", "List of configuration files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ListConfigs = QtWidgets.QWidget()
    ui = Ui_ListConfigs()
    ui.setupUi(ListConfigs)
    ListConfigs.show()
    sys.exit(app.exec_())
